### ISSUE TITLE
Seeing IIIF Viewer and Georeference Viewer at the same time for some records

### ISSUE THREAD

**Issue by srappel** [bplmaps/blacklight-allmaps#28]
test fixture harvard-g4124-m2-1855-m3 not affected, but these from UMN are in AGSL GeoDiscovery:

p16022coll230:1933

p16022coll230:360

p16022coll230:4038

Example:
![Screenshot 2024-03-29 at 08-44-13 1929 Illinois motor trails are calling - AGSL GeoDiscovery](https://github.com/bplmaps/blacklight-allmaps/assets/12561339/1d85298f-921f-4684-bc15-15b233e6ebf7)

**Comment by ewlarson** [comment]
@srappel // GBL's default IIIF item viewer overwrites the classes on the item viewer div. Wrapping GBL's item viewer in another wrapper div resolved this issue. Fix will be in v0.1.1.
